baseURL = "https://devinschulz.com/"
enableRobotsTXT = true
googleAnalytics = "UA-48758540-1"
languageCode = "en"
metaDataFormat = "toml"
title = "Devin Schulz"
summaryLength = 40
enableGitInfo = true
disqusShortname = "devinschulz"

pygmentsCodeFences = true
pygmentsUseClasses = true

[permalinks]
  posts = ":title/"

[author]
  name = "Devin Schulz"
  twitter = "devinschulz_"

[params]
  description = "Articles about React, JavaScript, testing, best practices, performance, and everything else related to front-end development."
  brandColor = "#3455db"
  dateFormat = "January 2, 2006"
  githubRepo = "https://github.com/devinschulz/blog"
  commentsEnabled = true
  twitterShare = "/images/share/twitter-share.jpg"
  facebookShare = "/images/share/facebook-share.jpg"

[[menu.footer]]
  name = "Posts"
  identifier = "posts"
  url = "/posts/"
  weight = 10

[[menu.footer]]
  name = "Sitemap"
  identifier = "sitemap"
  url = "/sitemap.xml"
  weight = 60

[[menu.footer]]
  name = "RSS"
  identifier = "rss"
  url = "/posts/index.xml"
  weight = 70

[[menu.social]]
  name = "Github"
  url = "https://github.com/devinschulz"
  weight = 10
[[menu.social]]
  name = "Twitter"
  url = "https://twitter.com/devinschulz_"
  weight = 20
[[menu.social]]
  name = "Dribbble"
  url = "https://dribbble.com/idev"
  weight = 30
[[menu.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/devinschulz"
  weight = 40
[[menu.social]]
  name = "Keybase"
  url = "https://keybase.io/devinschulz"
  weight = 50

