[build]
  publish = "public"
  command = "NODE_ENV=production && gulp netlify && hugo"

[context.production.environment]
  HUGO_VERSION = "0.37.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.37.1"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.37.1"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
